<?php

declare(strict_types=1);

namespace Laraflow\Export;

use Laraflow\Data\WorkflowDefinition;
use Laraflow\Data\WorkflowMeta;

final class PhpExporter
{
    public static function export(WorkflowDefinition $definition, WorkflowMeta $meta): string
    {
        $places = [];

        foreach ($definition->places as $place) {
            if ($place->metadata !== null && count($place->metadata) > 0) {
                $metaStr = self::exportArray($place->metadata, 3);
                $places[] = "        new Place(name: '{$place->name}', metadata: {$metaStr})";
            } else {
                $places[] = "        new Place(name: '{$place->name}')";
            }
        }

        $transitions = [];

        foreach ($definition->transitions as $t) {
            $parts = ["            name: '{$t->name}'"];
            $parts[] = '            froms: ' . self::exportStringArray($t->froms);
            $parts[] = '            tos: ' . self::exportStringArray($t->tos);

            if ($t->guard !== null) {
                $parts[] = "            guard: '" . addslashes($t->guard) . "'";
            }

            if ($t->consumeWeight !== null) {
                $parts[] = "            consumeWeight: {$t->consumeWeight}";
            }

            if ($t->produceWeight !== null) {
                $parts[] = "            produceWeight: {$t->produceWeight}";
            }

            if ($t->metadata !== null && count($t->metadata) > 0) {
                $parts[] = '            metadata: ' . self::exportArray($t->metadata, 3);
            }

            $transitions[] = "        new Transition(\n" . implode(",\n", $parts) . ",\n        )";
        }

        $placesStr = implode(",\n", $places);
        $transitionsStr = implode(",\n", $transitions);
        $initialMarkingStr = self::exportStringArray($definition->initialMarking);
        $typeClass = $definition->type->value === 'state_machine' ? 'StateMachine' : 'Workflow';
        $markingStoreClass = $meta->markingStore->value === 'property' ? 'Property' : 'Method';

        return <<<PHP
<?php

// Generated by Laraflow

use Laraflow\Data\Place;
use Laraflow\Data\Transition;
use Laraflow\Data\WorkflowDefinition;
use Laraflow\Data\WorkflowMeta;
use Laraflow\Enums\MarkingStoreType;
use Laraflow\Enums\WorkflowType;

return [
    'definition' => new WorkflowDefinition(
        name: '{$definition->name}',
        type: WorkflowType::{$typeClass},
        places: [
{$placesStr},
        ],
        transitions: [
{$transitionsStr},
        ],
        initialMarking: {$initialMarkingStr},
    ),
    'meta' => new WorkflowMeta(
        name: '{$meta->name}',
        type: WorkflowType::{$typeClass},
        markingStore: MarkingStoreType::{$markingStoreClass},
        initialMarking: {$initialMarkingStr},
        supports: '{$meta->supports}',
        property: '{$meta->property}',
    ),
];

PHP;
    }

    /**
     * @param  array<string>  $arr
     */
    private static function exportStringArray(array $arr): string
    {
        $items = array_map(fn ($s) => "'{$s}'", $arr);

        return '[' . implode(', ', $items) . ']';
    }

    /**
     * @param  array<string, string>  $arr
     */
    private static function exportArray(array $arr, int $depth = 1): string
    {
        $indent = str_repeat('    ', $depth);
        $items = [];

        foreach ($arr as $key => $value) {
            $items[] = "{$indent}'{$key}' => '{$value}'";
        }

        $innerIndent = str_repeat('    ', $depth - 1);

        return "[\n" . implode(",\n", $items) . ",\n{$innerIndent}]";
    }
}
